CREATE TABLE Users (
  id SERIAL PRIMARY KEY,
  uname TEXT NOT NULL UNIQUE,
  pw_hash TEXT NOT NULL,
  dm_link TEXT NOT NULL UNIQUE
);
CREATE TABLE Admins (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES Users (id)
);
CREATE TABLE Groups (
  id SERIAL PRIMARY KEY,
  gname TEXT NOT NULL UNIQUE,
  restriction TEXT NOT NULL,
  admin_id INTEGER NOT NULL REFERENCES Admins (id)
);
CREATE TABLE Topics (
  id SERIAL PRIMARY KEY,
  topic TEXT NOT NULL UNIQUE
);
CREATE TABLE Chats (
  id SERIAL PRIMARY KEY,
  cname TEXT NOT NULL,
  topic_id INTEGER REFERENCES Topics (id),
  group_id INTEGER REFERENCES Groups (id),
  link TEXT NOT NULL,
  moderator_id INTEGER REFERENCES Users (id)
);
CREATE TABLE Records (
    id SERIAL PRIMARY KEY,
    action TEXT NOT NULL,
    user_id INTEGER NOT NULL REFERENCES Users (id),
    action_time TIMESTAMP NOT NULL
);